;;; templates.el --- Stored email templates -*- lexical-binding: t; -*-

;; This file is auto-generated by emacs-email-templates package.
;; Do not edit manually.

(setq emacs-email-templates-list
      '((:name "Greetings"
               :subject "Greetings from Your Name"
               :body "Hello Recipient Name,\n\nThis is a sample email template.\n\nBest regards,\nYour Name")
        (:name "Follow-Up"
               :subject "Following Up on Project"
               :body "Hi Recipient Name,\n\nJust following up on Project.\n\nRegards,\nYour Name")))
